if $programname == 'unbound' then {
    action(
        type="omfile"
        file="/var/log/dns-soc/unbound.log"
        fileCreateMode="0640"
        fileOwner="syslog"
        fileGroup="splunkfwd"
    )
}
