flowchart TB
    Registrar[Hostinger<br/>Registrar]
    TLD[.tech registry / DNS hierarchy]
    Parent[Route 53 Parent Zone<br/>abdul4rehman215.tech]
    ParentSite[Parent A<br/>2.57.91.91]
    ParentMail[Parent mail / TXT / CNAME records]
    ChildNS[NS delegation<br/>soclab.abdul4rehman215.tech]
    Child[Route 53 Child Zone<br/>soclab.abdul4rehman215.tech]
    Apex[A<br/>soclab -> 100.49.192.164]
    WWW[CNAME<br/>www CNAME to soclab]
    TXT[TXT<br/>DNS SOC Training Lab]
    Web[dns-soc-web01<br/>EIP 100.49.192.164]

    Registrar -. registered nameservers .-> TLD
    TLD --> Parent
    Parent --> ParentSite
    Parent --> ParentMail
    Parent --> ChildNS
    ChildNS --> Child
    Child --> Apex
    Child --> WWW
    Child --> TXT
    Apex --> Web
    WWW --> Apex
